# Full Boxscore Dataset

In [90]:
import pandas as pd

In [91]:
df = pd.read_csv('boxscore.csv')
print(df)

         Unnamed: 0  Season   Game_ID      PLAYER_NAME Team     GAME_DATE  \
0            531380    1946  24600034    Adolph Hoefer  HUS  NOV 19, 1946
1            531378    1946  24600045    Adolph Hoefer  HUS  NOV 23, 1946
2            531379    1946  24600042    Adolph Hoefer  HUS  NOV 22, 1946
3            531377    1946  24600051    Adolph Hoefer  HUS  NOV 26, 1946
4            531376    1946  24600061    Adolph Hoefer  HUS  NOV 29, 1946
...             ...     ...       ...              ...  ...           ...
1309773     1282549    2023  22200663  Ziaire Williams  MEM  JAN 16, 2023
1309774     1282548    2023  22200672  Ziaire Williams  MEM  JAN 18, 2023
1309775     1282547    2023  22200690  Ziaire Williams  MEM  JAN 20, 2023
1309776     1282546    2023  22200703  Ziaire Williams  MEM  JAN 22, 2023
1309777     1283972    2023  22200554  Zion Williamson  NOP  JAN 02, 2023

             MATCHUP WL  MIN  FGM  ...  DREB  REB  AST  STL  BLK  TOV   PF  \
0        HUS vs. CLR  L    0    0  ...   NaN  NaN  NaN  NaN  NaN  NaN  1.0
1          HUS @ WAS  L    0    3  ...   NaN  NaN  NaN  NaN  NaN  NaN  NaN
2        HUS vs. BOS  W    0    1  ...   NaN  NaN  NaN  NaN  NaN  NaN  NaN
3        HUS vs. WAS  L    0    5  ...   NaN  NaN  NaN  NaN  NaN  NaN  NaN
4        HUS vs. CLR  L    0    0  ...   NaN  NaN  NaN  NaN  NaN  NaN  5.0
...              ... ..  ...  ...  ...   ...  ...  ...  ...  ...  ...  ...
1309773  MEM vs. PHX  W   17    1  ...   2.0  3.0  0.0  0.0  0.0  0.0  3.0
1309774  MEM vs. CLE  W   17    1  ...   0.0  0.0  1.0  0.0  0.0  0.0  1.0
1309775    MEM @ LAL  L   18    1  ...   2.0  3.0  2.0  0.0  0.0  0.0  5.0
1309776    MEM @ PHX  L   26    6  ...   4.0  5.0  0.0  0.0  0.0  3.0  2.0
1309777    NOP @ PHI  L   28   10  ...   6.0  6.0  7.0  0.0  0.0  5.0  1.0

         PTS  PLUS_MINUS  VIDEO_AVAILABLE
0          0         NaN                0
1          7         NaN                0
2          6         NaN                0
3         10         NaN                0
4          2         NaN                0
...      ...         ...              ...
1309773    3        14.0                1
1309774    3        -8.0                1
1309775    2        -2.0                1
1309776   16         5.0                1
1309777   26         6.0                1

[1309778 rows x 29 columns]

In [92]:
df.tail(20)

,Unnamed: 0,Season,Game_ID,PLAYER_NAME,Team,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
1309758,1282539,2023,22200805,Ziaire Williams,MEM,"FEB 05, 2023",MEM vs. TOR,L,11,1,...,1.0,2.0,2.0,0.0,0.0,1.0,1.0,2,-3.0,1
1309759,1282538,2023,22200841,Ziaire Williams,MEM,"FEB 10, 2023",MEM vs. MIN,W,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1
1309760,1282537,2023,22200907,Ziaire Williams,MEM,"FEB 25, 2023",MEM vs. DEN,W,4,0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0,-10.0,1
1309761,1282536,2023,22200927,Ziaire Williams,MEM,"FEB 28, 2023",MEM vs. LAL,W,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1
1309762,1282535,2023,22200938,Ziaire Williams,MEM,"MAR 01, 2023",MEM @ HOU,W,5,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,-9.0,1
1309763,1282534,2023,22200970,Ziaire Williams,MEM,"MAR 05, 2023",MEM @ LAC,L,6,0,...,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0,-3.0,1
1309764,1282533,2023,22200984,Ziaire Williams,MEM,"MAR 07, 2023",MEM @ LAL,L,5,1,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,2,-1.0,1
1309765,1282555,2023,22200564,Ziaire Williams,MEM,"JAN 04, 2023",MEM @ CHA,W,7,1,...,3.0,6.0,0.0,0.0,0.0,4.0,3.0,5,-10.0,1
1309766,1282554,2023,22200576,Ziaire Williams,MEM,"JAN 05, 2023",MEM @ ORL,W,14,6,...,1.0,1.0,0.0,0.0,0.0,1.0,2.0,16,13.0,1
1309767,1282553,2023,22200600,Ziaire Williams,MEM,"JAN 08, 2023",MEM vs. UTA,W,18,3,...,2.0,2.0,0.0,1.0,0.0,0.0,1.0,9,-5.0,1
1309768,1282552,2023,22200608,Ziaire Williams,MEM,"JAN 09, 2023",MEM vs. SAS,W,23,4,...,4.0,5.0,0.0,0.0,1.0,1.0,1.0,11,4.0,1
1309769,1282551,2023,22200623,Ziaire Williams,MEM,"JAN 11, 2023",MEM vs. SAS,W,26,4,...,0.0,0.0,1.0,1.0,0.0,1.0,3.0,9,7.0,1
1309770,1282550,2023,22200643,Ziaire Williams,MEM,"JAN 14, 2023",MEM @ IND,W,28,6,...,2.0,2.0,2.0,1.0,1.0,1.0,2.0,13,14.0,1
1309771,1282545,2023,22200712,Ziaire Williams,MEM,"JAN 23, 2023",MEM @ SAC,L,17,3,...,1.0,2.0,2.0,1.0,0.0,0.0,2.0,9,-22.0,1
1309772,1282543,2023,22200737,Ziaire Williams,MEM,"JAN 27, 2023",MEM @ MIN,L,26,3,...,2.0,2.0,0.0,2.0,0.0,3.0,0.0,7,-7.0,1
1309773,1282549,2023,22200663,Ziaire Williams,MEM,"JAN 16, 2023",MEM vs. PHX,W,17,1,...,2.0,3.0,0.0,0.0,0.0,0.0,3.0,3,14.0,1
1309774,1282548,2023,22200672,Ziaire Williams,MEM,"JAN 18, 2023",MEM vs. CLE,W,17,1,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,3,-8.0,1
1309775,1282547,2023,22200690,Ziaire Williams,MEM,"JAN 20, 2023",MEM @ LAL,L,18,1,...,2.0,3.0,2.0,0.0,0.0,0.0,5.0,2,-2.0,1
1309776,1282546,2023,22200703,Ziaire Williams,MEM,"JAN 22, 2023",MEM @ PHX,L,26,6,...,4.0,5.0,0.0,0.0,0.0,3.0,2.0,16,5.0,1
1309777,1283972,2023,22200554,Zion Williamson,NOP,"JAN 02, 2023",NOP @ PHI,L,28,10,...,6.0,6.0,7.0,0.0,0.0,5.0,1.0,26,6.0,1

In [93]:
df.to_csv('box_score.csv')

# NBA Season Dates
## OCT 18, 2022 - APR 9, 2023
## OCT 19, 2021 - APR 10, 2022
## DEC 22, 2020 - MAY 16, 2021
## OCT 22, 2019 - AUG 14, 2020

In [94]:
df['GAME_DATE'] = pd.to_datetime(df['GAME_DATE'])

In [95]:
df.tail(20)

,Unnamed: 0,Season,Game_ID,PLAYER_NAME,Team,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
1309758,1282539,2023,22200805,Ziaire Williams,MEM,2023-02-05,MEM vs. TOR,L,11,1,...,1.0,2.0,2.0,0.0,0.0,1.0,1.0,2,-3.0,1
1309759,1282538,2023,22200841,Ziaire Williams,MEM,2023-02-10,MEM vs. MIN,W,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1
1309760,1282537,2023,22200907,Ziaire Williams,MEM,2023-02-25,MEM vs. DEN,W,4,0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0,-10.0,1
1309761,1282536,2023,22200927,Ziaire Williams,MEM,2023-02-28,MEM vs. LAL,W,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1
1309762,1282535,2023,22200938,Ziaire Williams,MEM,2023-03-01,MEM @ HOU,W,5,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,-9.0,1
1309763,1282534,2023,22200970,Ziaire Williams,MEM,2023-03-05,MEM @ LAC,L,6,0,...,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0,-3.0,1
1309764,1282533,2023,22200984,Ziaire Williams,MEM,2023-03-07,MEM @ LAL,L,5,1,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,2,-1.0,1
1309765,1282555,2023,22200564,Ziaire Williams,MEM,2023-01-04,MEM @ CHA,W,7,1,...,3.0,6.0,0.0,0.0,0.0,4.0,3.0,5,-10.0,1
1309766,1282554,2023,22200576,Ziaire Williams,MEM,2023-01-05,MEM @ ORL,W,14,6,...,1.0,1.0,0.0,0.0,0.0,1.0,2.0,16,13.0,1
1309767,1282553,2023,22200600,Ziaire Williams,MEM,2023-01-08,MEM vs. UTA,W,18,3,...,2.0,2.0,0.0,1.0,0.0,0.0,1.0,9,-5.0,1
1309768,1282552,2023,22200608,Ziaire Williams,MEM,2023-01-09,MEM vs. SAS,W,23,4,...,4.0,5.0,0.0,0.0,1.0,1.0,1.0,11,4.0,1
1309769,1282551,2023,22200623,Ziaire Williams,MEM,2023-01-11,MEM vs. SAS,W,26,4,...,0.0,0.0,1.0,1.0,0.0,1.0,3.0,9,7.0,1
1309770,1282550,2023,22200643,Ziaire Williams,MEM,2023-01-14,MEM @ IND,W,28,6,...,2.0,2.0,2.0,1.0,1.0,1.0,2.0,13,14.0,1
1309771,1282545,2023,22200712,Ziaire Williams,MEM,2023-01-23,MEM @ SAC,L,17,3,...,1.0,2.0,2.0,1.0,0.0,0.0,2.0,9,-22.0,1
1309772,1282543,2023,22200737,Ziaire Williams,MEM,2023-01-27,MEM @ MIN,L,26,3,...,2.0,2.0,0.0,2.0,0.0,3.0,0.0,7,-7.0,1
1309773,1282549,2023,22200663,Ziaire Williams,MEM,2023-01-16,MEM vs. PHX,W,17,1,...,2.0,3.0,0.0,0.0,0.0,0.0,3.0,3,14.0,1
1309774,1282548,2023,22200672,Ziaire Williams,MEM,2023-01-18,MEM vs. CLE,W,17,1,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,3,-8.0,1
1309775,1282547,2023,22200690,Ziaire Williams,MEM,2023-01-20,MEM @ LAL,L,18,1,...,2.0,3.0,2.0,0.0,0.0,0.0,5.0,2,-2.0,1
1309776,1282546,2023,22200703,Ziaire Williams,MEM,2023-01-22,MEM @ PHX,L,26,6,...,4.0,5.0,0.0,0.0,0.0,3.0,2.0,16,5.0,1
1309777,1283972,2023,22200554,Zion Williamson,NOP,2023-01-02,NOP @ PHI,L,28,10,...,6.0,6.0,7.0,0.0,0.0,5.0,1.0,26,6.0,1

In [96]:
# 2022 - 2023 season #filtered1
start_date = '2022-10-18'
end_date = '2023-04-09'
filtered1_df = df[(df['GAME_DATE'] >= start_date) & (df['GAME_DATE'] <= end_date)]
filtered1_df.to_csv('filtered1_dataframe.csv', index=False)

In [97]:
filtered1_df.columns.values

array(['Unnamed: 0', 'Season', 'Game_ID', 'PLAYER_NAME', 'Team',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS',
       'VIDEO_AVAILABLE'], dtype=object)

In [98]:
filtered1_df_teams = filtered1_df['Team'].unique()
filtered1_df_teams_list = filtered1_df_teams.tolist()

filtered1_df_players = filtered1_df['PLAYER_NAME'].unique()
filtered1_df_players_list = filtered1_df_players.tolist()

In [99]:
# 2021 - 2022 season #filtered2
start_date = '2021-10-19'
end_date = '2022-04-10'
filtered2_df = df[(df['GAME_DATE'] >= start_date) & (df['GAME_DATE'] <= end_date)]
filtered2_df.to_csv('filtered2_dataframe.csv', index=False)

In [100]:
filtered2_df_teams = filtered2_df['Team'].unique()
filtered2_df_teams_list = filtered2_df_teams.tolist()

filtered2_df_players = filtered2_df['PLAYER_NAME'].unique()
filtered2_df_players_list = filtered2_df_players.tolist()

In [101]:
# 2020 - 2021 season #filtered3
start_date = '2020-12-22'
end_date = '2021-05-16'
filtered3_df = df[(df['GAME_DATE'] >= start_date) & (df['GAME_DATE'] <= end_date)]
filtered3_df.to_csv('filtered3_dataframe.csv', index=False)

In [102]:
filtered3_df_teams = filtered3_df['Team'].unique()
filtered3_df_teams_list = filtered3_df_teams.tolist()

filtered3_df_players = filtered3_df['PLAYER_NAME'].unique()
filtered3_df_players_list = filtered3_df_players.tolist()

In [103]:
# 2019 - 2020 season #filtered4
start_date = '2019-10-22'
end_date = '2020-08-14'
filtered4_df = df[(df['GAME_DATE'] >= start_date) & (df['GAME_DATE'] <= end_date)]
filtered4_df.to_csv('filtered4_dataframe.csv', index=False)

In [104]:
filtered4_df_teams = filtered4_df['Team'].unique()
filtered4_df_teams_list = filtered4_df_teams.tolist()

filtered4_df_players = filtered4_df['PLAYER_NAME'].unique()
filtered4_df_players_list = filtered4_df_players.tolist()

# 2022 - 2023 Dataset
## filtered1_df

In [105]:
filtered1_df.columns

Index(['Unnamed: 0', 'Season', 'Game_ID', 'PLAYER_NAME', 'Team', 'GAME_DATE',
       'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE'],
      dtype='object')

In [106]:
filtered1_df.head(5)

,Unnamed: 0,Season,Game_ID,PLAYER_NAME,Team,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
1269955,447141,2022,22200316,A.J. Green,MIL,2022-11-30,MIL @ NYK,W,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1
1269956,447134,2022,22200533,A.J. Green,MIL,2022-12-30,MIL vs. MIN,W,22,2,...,2.0,3.0,1.0,1.0,0.0,0.0,4.0,7,9.0,1
1269957,447135,2022,22200442,A.J. Green,MIL,2022-12-17,MIL vs. UTA,W,4,1,...,0.0,0.0,1.0,0.0,0.0,0.0,2.0,3,3.0,1
1269958,447136,2022,22200425,A.J. Green,MIL,2022-12-15,MIL @ MEM,L,14,4,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,10,3.0,1
1269959,447137,2022,22200410,A.J. Green,MIL,2022-12-13,MIL vs. GSW,W,3,1,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2,-2.0,1

In [107]:
filtered1_df_teams = filtered1_df['Team'].unique()
filtered1_df_teams_list = filtered1_df_teams.tolist()

filtered1_df_players = filtered1_df['PLAYER_NAME'].unique()
filtered1_df_players_list = filtered1_df_players.tolist()

In [108]:
filtered1_df.columns

Index(['Unnamed: 0', 'Season', 'Game_ID', 'PLAYER_NAME', 'Team', 'GAME_DATE',
       'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE'],
      dtype='object')

## column names that are important 
### relevant for DraftKings fantasy predictions: points (PTS), 3 points made (3P), total rebounds (TRB), assists (AST), steals (STL), blocks (BLK), turnovers (TOV), double doubles (DD), and triple doubles (TD).
### such columns are named 'PTS' (pts), 'FG3M' (3p), 'REB' (trb), 'AST' (ast), 'STL' (stl), 'BLK' (blk), 'TOV' (tov)
### we still need to make a column that has 'DD' and 'TD'. A double-double is defined as obtaining 10 or more in two categories of either points, rebounds, assists, steals, or blocks. (PTS, REB, AST, STL, BLK). A triple double is similar for 3 or more.

In [109]:
df = filtered1_df

df['DD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 2
df['DD'] = df['DD'].map({True: 'yes', False: 'no'})

df['TD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 3
df['TD'] = df['TD'].map({True: 'yes', False: 'no'})

df.to_csv('filtered1_df.csv', index=False)
filtered1_df = df

## Now let us add the new columns 'DD' and 'TD' to all the rest of the filtered datasets.

In [110]:
df = filtered2_df

df['DD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 2
df['DD'] = df['DD'].map({True: 'yes', False: 'no'})

df['TD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 3
df['TD'] = df['TD'].map({True: 'yes', False: 'no'})

df.to_csv('filtered1_df.csv', index=False)
filtered2_df = df

In [111]:
df = filtered3_df

df['DD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 2
df['DD'] = df['DD'].map({True: 'yes', False: 'no'})

df['TD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 3
df['TD'] = df['TD'].map({True: 'yes', False: 'no'})

df.to_csv('filtered1_df.csv', index=False)
filtered3_df = df

In [112]:
df = filtered4_df

df['DD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 2
df['DD'] = df['DD'].map({True: 'yes', False: 'no'})

df['TD'] = ((df['PTS'] >= 10) + (df['REB'] >= 10) + (df['AST'] >= 10) + 
            (df['STL'] >= 10) + (df['BLK'] >= 10)) >= 3
df['TD'] = df['TD'].map({True: 'yes', False: 'no'})

df.to_csv('filtered1_df.csv', index=False)
filtered4_df = df

## Now let us return to the 2022-2023 dataset, filtered1_df to make another column that has the total number of fantasy points earned per game for each player.

In [113]:
def calculate_total_fantasy_points(lineup):
    total_points = 0
    
    for player in lineup:
        points = player['points']
        made_three_pt = player['made_three_pt']
        rebounds = player['rebounds']
        assists = player['assists']
        steals = player['steals']
        blocks = player['blocks']
        turnovers = player['turnovers']
        double_double = player['double_double']
        triple_double = player['triple_double']
        
        total_points += points
        total_points += made_three_pt * 0.5
        total_points += rebounds * 1.25
        total_points += assists * 1.5
        total_points += steals * 2
        total_points += blocks * 2
        total_points -= turnovers * 0.5
        if double_double:
            total_points += 1.5
        if triple_double:
            total_points += 3
    
    return total_points

In [115]:
class CustomDataFrame(pd.DataFrame):
    @staticmethod
    def calculate_total_fantasy_points(row):
        points = row['FGM']
        made_three_pt = row['FG3M']
        rebounds = row['REB']
        assists = row['AST']
        steals = row['STL']
        blocks = row['BLK']
        turnovers = row['TOV']
        double_double = row['DD']
        triple_double = row['TD']

        total_points = (
            points
            + made_three_pt * 0.5
            + rebounds * 1.25
            + assists * 1.5  
            + steals * 2
            + blocks * 2
            - turnovers * 0.5  
        )
        if double_double:
            total_points += 1.5
        if triple_double:
            total_points += 3

        return total_points

df = filtered1_df
df['total_fantasy_points'] = df.apply(CustomDataFrame.calculate_total_fantasy_points, axis=1)
df.to_csv('filtered1_df.csv', index=False)

filtered1_df = df

In [116]:
filtered1_df

,Unnamed: 0,Season,Game_ID,PLAYER_NAME,Team,GAME_DATE,MATCHUP,WL,MIN,FGM,...,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,DD,TD,total_fantasy_points
1269955,447141,2022,22200316,A.J. Green,MIL,2022-11-30,MIL @ NYK,W,0,0,...,0.0,0.0,0.0,0.0,0,0.0,1,no,no,4.50
1269956,447134,2022,22200533,A.J. Green,MIL,2022-12-30,MIL vs. MIN,W,22,2,...,1.0,0.0,0.0,4.0,7,9.0,1,no,no,14.75
1269957,447135,2022,22200442,A.J. Green,MIL,2022-12-17,MIL vs. UTA,W,4,1,...,0.0,0.0,0.0,2.0,3,3.0,1,no,no,7.50
1269958,447136,2022,22200425,A.J. Green,MIL,2022-12-15,MIL @ MEM,L,14,4,...,0.0,0.0,1.0,1.0,10,3.0,1,no,no,10.25
1269959,447137,2022,22200410,A.J. Green,MIL,2022-12-13,MIL vs. GSW,W,3,1,...,0.0,0.0,0.0,1.0,2,-2.0,1,no,no,7.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1309773,1282549,2023,22200663,Ziaire Williams,MEM,2023-01-16,MEM vs. PHX,W,17,1,...,0.0,0.0,0.0,3.0,3,14.0,1,no,no,9.75
1309774,1282548,2023,22200672,Ziaire Williams,MEM,2023-01-18,MEM vs. CLE,W,17,1,...,0.0,0.0,0.0,1.0,3,-8.0,1,no,no,7.00
1309775,1282547,2023,22200690,Ziaire Williams,MEM,2023-01-20,MEM @ LAL,L,18,1,...,0.0,0.0,0.0,5.0,2,-2.0,1,no,no,12.25
1309776,1282546,2023,22200703,Ziaire Williams,MEM,2023-01-22,MEM @ PHX,L,26,6,...,0.0,0.0,3.0,2.0,16,5.0,1,no,no,16.75
1309777,1283972,2023,22200554,Zion Williamson,NOP,2023-01-02,NOP @ PHI,L,28,10,...,0.0,0.0,5.0,1.0,26,6.0,1,no,no,30.00

In [117]:
# check to make sure the function is working
tail_filter1 = filtered1_df.tail(5)
tail_filter1.to_csv('filtered1_tail_df.csv', index=False)

## Now let us add the new columns 'total_fantasy_points' to all the rest of the filtered datasets.

In [118]:
df = filtered1_df

df['total_fantasy_points'] = df.apply(CustomDataFrame.calculate_total_fantasy_points, axis=1)

df.to_csv('filtered1_df.csv', index=False)

filtered1_df = df

In [119]:
df = filtered2_df
df['total_fantasy_points'] = df.apply(CustomDataFrame.calculate_total_fantasy_points, axis=1)
df.to_csv('filtered2_df.csv', index=False)

filtered2_df = df

In [120]:
df = filtered3_df
df['total_fantasy_points'] = df.apply(CustomDataFrame.calculate_total_fantasy_points, axis=1)
df.to_csv('filtered3_df.csv', index=False)

filtered3_df = df

In [121]:
df = filtered4_df
df['total_fantasy_points'] = df.apply(CustomDataFrame.calculate_total_fantasy_points, axis=1)
df.to_csv('filtered4_df.csv', index=False)

filtered4_df = df

In [122]:
filtered1_df.tail(5)

,Unnamed: 0,Season,Game_ID,PLAYER_NAME,Team,GAME_DATE,MATCHUP,WL,MIN,FGM,...,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,DD,TD,total_fantasy_points
1309773,1282549,2023,22200663,Ziaire Williams,MEM,2023-01-16,MEM vs. PHX,W,17,1,...,0.0,0.0,0.0,3.0,3,14.0,1,no,no,9.75
1309774,1282548,2023,22200672,Ziaire Williams,MEM,2023-01-18,MEM vs. CLE,W,17,1,...,0.0,0.0,0.0,1.0,3,-8.0,1,no,no,7.00
1309775,1282547,2023,22200690,Ziaire Williams,MEM,2023-01-20,MEM @ LAL,L,18,1,...,0.0,0.0,0.0,5.0,2,-2.0,1,no,no,12.25
1309776,1282546,2023,22200703,Ziaire Williams,MEM,2023-01-22,MEM @ PHX,L,26,6,...,0.0,0.0,3.0,2.0,16,5.0,1,no,no,16.75
1309777,1283972,2023,22200554,Zion Williamson,NOP,2023-01-02,NOP @ PHI,L,28,10,...,0.0,0.0,5.0,1.0,26,6.0,1,no,no,30.00

## Now let us add a column 'POS' to each df to indicate each players position.

In [123]:
df_pos = pd.read_csv('ball-ref-03.csv')
df1 = df_pos[['Player_Name', 'Pos']]
df2 = filtered1_df

In [124]:
merged_df = df2.merge(df1, left_on='PLAYER_NAME', right_on='Player_Name', how='left')
merged_df.drop('Player_Name', axis=1, inplace=True)
merged_df.rename(columns={'Pos': 'POS'}, inplace=True)
player_name_index = merged_df.columns.get_loc('PLAYER_NAME')
pos_column = merged_df.pop('POS')
merged_df.insert(player_name_index + 1, 'POS', pos_column)
merged_df.to_csv('merged_dataframe.csv', index=False)

filtered1_df = merged_df

In [125]:
df2 = filtered2_df

merged_df = df2.merge(df1, left_on='PLAYER_NAME', right_on='Player_Name', how='left')
merged_df.drop('Player_Name', axis=1, inplace=True)
merged_df.rename(columns={'Pos': 'POS'}, inplace=True)
player_name_index = merged_df.columns.get_loc('PLAYER_NAME')
pos_column = merged_df.pop('POS')
merged_df.insert(player_name_index + 1, 'POS', pos_column)
merged_df.to_csv('merged_dataframe.csv', index=False)

filtered2_df = merged_df

In [126]:
df2 = filtered3_df

merged_df = df2.merge(df1, left_on='PLAYER_NAME', right_on='Player_Name', how='left')
merged_df.drop('Player_Name', axis=1, inplace=True)
merged_df.rename(columns={'Pos': 'POS'}, inplace=True)
player_name_index = merged_df.columns.get_loc('PLAYER_NAME')
pos_column = merged_df.pop('POS')
merged_df.insert(player_name_index + 1, 'POS', pos_column)
merged_df.to_csv('merged_dataframe.csv', index=False)

filtered3_df = merged_df

In [127]:
df2 = filtered4_df

merged_df = df2.merge(df1, left_on='PLAYER_NAME', right_on='Player_Name', how='left')
merged_df.drop('Player_Name', axis=1, inplace=True)
merged_df.rename(columns={'Pos': 'POS'}, inplace=True)
player_name_index = merged_df.columns.get_loc('PLAYER_NAME')
pos_column = merged_df.pop('POS')
merged_df.insert(player_name_index + 1, 'POS', pos_column)
merged_df.to_csv('merged_dataframe.csv', index=False)

filtered4_df = merged_df

## Let us clean up the data further by deleting all rows with na values for positions.

In [128]:
filtered1_df.dropna(subset=['POS'], inplace=True)
filtered2_df.dropna(subset=['POS'], inplace=True)
filtered3_df.dropna(subset=['POS'], inplace=True)
filtered4_df.dropna(subset=['POS'], inplace=True)

In [129]:
filtered1_df.to_csv('filtered1_df.csv')
filtered2_df.to_csv('filtered2_df.csv')
filtered3_df.to_csv('filtered3_df.csv')
filtered4_df.to_csv('filtered4_df.csv')